	import { StyleSheet } from 'react-native';
	import { colors } from '../../colors/colors';

	export default StyleSheet.create({
				headerTitle: {
					fontSize: 28,
					fontWeight: 'bold',
					color: colors.secondary,
					textAlign: 'center',
					letterSpacing: 0.5,
					marginTop: 32,
					marginBottom: 12,
					paddingBottom: 12,
					borderBottomWidth: 1,
					borderBottomColor: colors.border || '#e0e0e0',
					backgroundColor: 'transparent',
				},
	container: {
		flex: 1,
		backgroundColor: colors.background,
		padding: 20,
	},
		input: {
			flex: 1,
			borderWidth: 1.5,
			borderColor: colors.secondary,
			borderRadius: 8,
			paddingHorizontal: 10,
			paddingVertical: 0,
			backgroundColor: colors.inputBackground || '#f9f9f9',
			fontSize: 16,
			color: colors.text,
			shadowColor: colors.secondary,
			shadowOffset: { width: 0, height: 1 },
			shadowOpacity: 0.08,
			shadowRadius: 2,
			elevation: 1,
			height: 48,
			minHeight: 48,
			textAlignVertical: 'center',
		},
		inputIconRow: {
			flexDirection: 'row',
			alignItems: 'center',
			marginBottom: 10,
		},
		inputIconRowBox: {
			flexDirection: 'row',
			alignItems: 'center',
			borderWidth: 1.5,
			borderColor: colors.secondary,
			borderRadius: 8,
			backgroundColor: colors.inputBackground || '#f9f9f9',
			marginBottom: 10,
			paddingHorizontal: 10,
			paddingVertical: 2,
			shadowColor: colors.secondary,
			shadowOffset: { width: 0, height: 1 },
			shadowOpacity: 0.08,
			shadowRadius: 2,
			elevation: 1,
		},
		inputBox: {
			flex: 1,
			fontSize: 16,
			color: colors.text,
			paddingVertical: 0,
			paddingHorizontal: 8,
			height: 48,
			minHeight: 48,
			backgroundColor: 'transparent',
			textAlignVertical: 'center',
		},
			buttonEndereco: {
				flexDirection: 'row',
				alignItems: 'center',
				backgroundColor: colors.primary,
				borderRadius: 8,
				padding: 12,
				marginVertical: 10,
				alignSelf: 'flex-start',
			},
			textButtonEndereco: {
				color: '#fff',
				fontWeight: 'bold',
				fontSize: 15,
			},
			modalContainer: {
				flex: 1,
				backgroundColor: 'rgba(0,0,0,0.3)',
				justifyContent: 'center',
				alignItems: 'center',
			},
			modalBox: {
				backgroundColor: '#fff',
				borderRadius: 12,
				padding: 20,
				width: '90%',
                height: '80%',
                shadowColor: '#000',
                shadowOffset: { width: 0, height: 2 },
                shadowOpacity: 0.25,
                shadowRadius: 4,
				elevation: 5,
			},
			modalServicoBox: {
				minHeight: 300,
			},
			modalTitle: {
				fontSize: 20,
				fontWeight: 'bold',
				marginBottom: 12,
				textAlign: 'center',
				color: colors.secondary,
			},
			servicoItem: {
				flexDirection: 'row',
				justifyContent: 'space-between',
				alignItems: 'center',
				paddingVertical: 8,
				borderBottomWidth: 1,
				borderBottomColor: colors.border || '#eee',
			},
			servicoInputRow: {
				flexDirection: 'row',
				alignItems: 'center',
				marginTop: 10,
			},
			buttonAddServico: {
				backgroundColor: colors.secondary,
				paddingVertical: 10,
				paddingHorizontal: 16,
				borderRadius: 8,
				marginLeft: 8,
			},
			buttonTextAddServico: {
				color: '#fff',
				fontWeight: 'bold',
			},
				buttonCloseModal: {
					backgroundColor: colors.error,
					paddingVertical: 14,
					paddingHorizontal: 0,
					borderRadius: 8,
					alignItems: 'center',
					justifyContent: 'center',
					minHeight: 48,
				},
			buttonTextCloseModal: {
				color: '#fff',
				fontWeight: 'bold',
			},
				buttonSaveModal: {
					backgroundColor: colors.success,
					paddingVertical: 14,
					paddingHorizontal: 0,
					borderRadius: 8,
					alignItems: 'center',
					justifyContent: 'center',
					minHeight: 48,
				},
			buttonTextSaveModal: {
				color: '#fff',
				fontWeight: 'bold',
			},
				buttonBuscarCep: {
					backgroundColor: colors.secondary,
					borderRadius: 8,
					marginLeft: 8,
					height: 48,
					minWidth: 48,
					alignItems: 'center',
					justifyContent: 'center',
					padding: 0,
				},
			buttonTextBuscarCep: {
				color: '#fff',
				fontWeight: 'bold',
			},
			footerRow: {
				flexDirection: 'row',
				justifyContent: 'space-between',
				marginTop: 10,
			},
			buttonFooter: {
				backgroundColor: colors.secondary,

				borderRadius: 8,
				alignItems: 'center',
                justifyContent: 'center',
				flex: 1,
				marginLeft: 8,
				shadowColor: colors.secondary,
				shadowOffset: { width: 0, height: 2 },
				shadowOpacity: 0.12,
				shadowRadius: 3,
				elevation: 2,
			},
			buttonFooterCancel: {
				backgroundColor: colors.background,
				borderWidth: 1.5,
				borderColor: colors.secondary,
				paddingVertical: 14,
				paddingHorizontal: 32,
				borderRadius: 8,
				alignItems: 'center',
				flex: 1,
				marginRight: 8,
			},
			buttonTextFooter: {
				color: '#fff',
				fontWeight: 'bold',
				fontSize: 16,
			},
			buttonTextCancel: {
				color: colors.secondary,
				fontWeight: 'bold',
				fontSize: 16,
			},
		});